# none [default] | windows | linux | osx | [windows, linux, ...]
os-lock = 'none'

[os.windows.default]
interpreter = 'bash'

[os.windows.ps1]
interpreter = 'powershell'
args = ['-ExecutionPolicy', 'Unrestricted', '-File']

[os.linux.sh]
interpreter = 'fakeshell'
args = ['--TestArg', '998']