# none [default] | windows | linux | osx | [windows, linux, ...]
os-lock = 'windows'

# powershell [default] | cmd | path-to-another-interpreter
#windows-interpreter = 'powershell'
#interpreter-args = ['-ExecutionPolicy', 'Unrestricted', '-File']
windows-interpreter = 'bash'